// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ7lxD0wI5a5w1VesxPoj2iP8rTUoMSvQ',
    appId: '1:674394725719:web:f788c9854f93ea5edc7212',
    messagingSenderId: '674394725719',
    projectId: 'redsocial-c6de9',
    authDomain: 'redsocial-c6de9.firebaseapp.com',
    storageBucket: 'redsocial-c6de9.appspot.com',
    measurementId: 'G-0M1C8HVQG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDade3OymXgHMwlbYhRLU1mCEfXaPXZ0NU',
    appId: '1:674394725719:android:465474fffa4cc662dc7212',
    messagingSenderId: '674394725719',
    projectId: 'redsocial-c6de9',
    storageBucket: 'redsocial-c6de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlRX7FytLplvqjor3uVf04YNk4nk-fxhg',
    appId: '1:674394725719:ios:0f07b89a682930dcdc7212',
    messagingSenderId: '674394725719',
    projectId: 'redsocial-c6de9',
    storageBucket: 'redsocial-c6de9.appspot.com',
    iosClientId: '674394725719-puh9fhp05r7sb2995beeog2qldiuk890.apps.googleusercontent.com',
    iosBundleId: 'com.example.redSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlRX7FytLplvqjor3uVf04YNk4nk-fxhg',
    appId: '1:674394725719:ios:0f07b89a682930dcdc7212',
    messagingSenderId: '674394725719',
    projectId: 'redsocial-c6de9',
    storageBucket: 'redsocial-c6de9.appspot.com',
    iosClientId: '674394725719-puh9fhp05r7sb2995beeog2qldiuk890.apps.googleusercontent.com',
    iosBundleId: 'com.example.redSocial',
  );
}
